"use client";

import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api";
import { ReportItem } from "@/types";
import { FolderOpen, Download, FileText, Calendar, ExternalLink } from "lucide-react";

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState<any | null>(null);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    setLoading(true);
    try {
      const data = await apiRequest<ReportItem[]>("/reports");
      setReports(data);
      if (data.length > 0 && !selectedReport) {
        inspectReport(data[0].id);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const inspectReport = async (id: string) => {
    try {
      const data = await apiRequest(`/reports/${id}`);
      setSelectedReport(data);
    } catch (e) {
      console.error(e);
    }
  };

  const downloadMarkdown = (report: any) => {
    const blob = new Blob([report.content_markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.title.toLowerCase().replace(/\s+/g, "_")}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 max-w-6xl">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-white">Generated Reports & Artifacts</h1>
          <p className="mt-1 text-sm text-slate-400">
            First-class analytical reports generated by AI agents across verified organizational data sources.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Report List */}
        <div className="space-y-3">
          <div className="text-xs font-semibold uppercase text-slate-400 tracking-wider">
            Saved Reports ({reports.length})
          </div>
          {reports.map((r) => (
            <div
              key={r.id}
              onClick={() => inspectReport(r.id)}
              className={`cursor-pointer rounded-xl border p-4 transition ${
                selectedReport?.id === r.id
                  ? "border-purple-500 bg-slate-900 shadow-md"
                  : "border-slate-800 bg-slate-900/50 hover:bg-slate-900"
              }`}
            >
              <div className="flex items-center space-x-2.5 truncate">
                <FolderOpen className="h-4 w-4 text-purple-400 flex-shrink-0" />
                <span className="font-semibold text-sm text-white truncate">{r.title}</span>
              </div>
              <p className="mt-2 text-xs text-slate-400 line-clamp-2">{r.summary || "No executive summary provided."}</p>
              <div className="mt-3 flex items-center justify-between text-[11px] text-slate-400 pt-2 border-t border-slate-800">
                <span className="flex items-center space-x-1">
                  <Calendar className="h-3 w-3" />
                  <span>{new Date(r.created_at).toLocaleDateString()}</span>
                </span>
                <span>{r.data_sources?.length || 0} Sources</span>
              </div>
            </div>
          ))}
        </div>

        {/* Report Viewer */}
        <div className="md:col-span-2 rounded-xl border border-slate-800 bg-slate-900/50 p-6 shadow-sm">
          {selectedReport ? (
            <div className="space-y-6">
              <div className="flex items-center justify-between border-b border-slate-800 pb-4">
                <div>
                  <h2 className="text-xl font-bold text-white">{selectedReport.title}</h2>
                  <div className="text-xs text-slate-400 mt-1">
                    Generated on {new Date(selectedReport.created_at).toLocaleString()}
                  </div>
                </div>

                <button
                  onClick={() => downloadMarkdown(selectedReport)}
                  className="flex items-center space-x-1.5 rounded-lg bg-aura-600/20 border border-aura-500/30 px-3 py-1.5 text-xs font-medium text-aura-300 hover:bg-aura-600/30 transition"
                >
                  <Download className="h-3.5 w-3.5" />
                  <span>Export Markdown</span>
                </button>
              </div>

              {selectedReport.summary && (
                <div className="rounded-lg bg-slate-800/40 border border-slate-700/50 p-4 text-xs text-slate-300">
                  <strong className="text-white block mb-1">Executive Summary:</strong>
                  {selectedReport.summary}
                </div>
              )}

              {/* Data Sources referenced */}
              {selectedReport.data_sources && selectedReport.data_sources.length > 0 && (
                <div>
                  <div className="text-xs font-semibold uppercase tracking-wider text-slate-400 mb-2">
                    Verified Sources & Citations
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {selectedReport.data_sources.map((src: string, idx: number) => (
                      <span
                        key={idx}
                        className="rounded bg-slate-800 px-2 py-1 text-xs font-mono text-aura-300 border border-slate-700"
                      >
                        [{idx + 1}] {src}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Markdown Content Viewer */}
              <div className="border border-slate-800 rounded-lg p-5 bg-slate-950/60 text-slate-200 text-sm whitespace-pre-wrap leading-relaxed font-sans">
                {selectedReport.content_markdown}
              </div>
            </div>
          ) : (
            <div className="py-20 text-center text-xs text-slate-500">Select a report to view details.</div>
          )}
        </div>
      </div>
    </div>
  );
}
